server:
  port: 9527
spring:
  application:
    name: cloud-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心创建动态路由的功能，以微服务名称进行路由，实现动态路由下的负载均衡，默认也是轮询请求的方式，8001,8002来回切换
      routes:
        - id: payment_routh           #路由id
          #uri: http://localhost:8001  #匹配后提供的路径地址
          uri: lb://cloud-payment-service #地址为注册中心注册的服务名，这里是eureka注册的服务名。 前缀lb为负载均衡的名称
        # filters:   配置过滤器
          predicates:                 #断言，路径匹配的进行路由
            - Path=/payment/get/** #路径匹配，多个匹配规则可以组合使用
            # - After             日期匹配，在某日期之后
            # - Before            日期匹配，在某日期之前  值使用ZonedDateTime类生成
            # - Between           两个日期之间，用逗号隔开，填两个日期值
            # - Cookie            Cookie匹配， 值有两个，第一个为cookie的name，第二个为匹配cookie name 对应value值的正则表达式。
            # - Header            Header匹配， 值有两个，第一个为header的name，第二个为匹配header name 对应value值的正则表达式。
            # - Host              主机匹配，支持模糊路径，例如 **.baidu.com,aaa** 多个值
            # - Method            请求方法匹配，GET
            # - Query             参数值匹配， 值有两个，第一个为参数key，第二个为匹配参数key的value值的正则表达式。
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka