server:
  port: 9527
spring:
  application:
    name: cloud-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心创建动态路由的功能，以微服务名称进行路由，实现动态路由下的负载均衡，默认也是轮询请求的方式，8001,8002来回切换
      routes:
        - id: payment_routh           #路由id
          #uri: http://localhost:8001  #匹配后提供的路径地址
          uri: lb://cloud-payment-service #地址为注册中心注册的服务名，这里是eureka注册的服务名。 前缀lb为负载均衡的名称
          predicates:                 #断言，路径匹配的进行路由
            - Path=/payment/get/**
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka