server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己就是注册中心，负责维护服务实例，不需要检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机构建defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #自我保护
    enable-self-preservation: true
    #超时剔除服务时间间隔，单位为秒
    eviction-interval-timer-in-ms: 2000
logging:
  level:
    com.netflix: warn